In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [84]:
df = pd.read_csv('bodyPerformance.csv')
df.head(10)

age gender  height_cm  weight_kg  body fat_%  diastolic  systolic  \
0  27.0      M      172.3      75.24        21.3       80.0     130.0   
1  25.0      M      165.0      55.80        15.7       77.0     126.0   
2  31.0      M      179.6      78.00        20.1       92.0     152.0   
3  32.0      M      174.5      71.10        18.4       76.0     147.0   
4  28.0      M      173.8      67.70        17.1       70.0     127.0   
5  36.0      F      165.4      55.40        22.0       64.0     119.0   
6  42.0      F      164.5      63.70        32.2       72.0     135.0   
7  33.0      M      174.9      77.20        36.9       84.0     137.0   
8  54.0      M      166.8      67.50        27.6       85.0     165.0   
9  28.0      M      185.0      84.60        14.4       81.0     156.0   

   gripForce  sit and bend forward_cm  sit-ups counts  broad jump_cm class  
0       54.9                     18.4            60.0          217.0     C  
1       36.4                     16.3            53.0          229.0     A  
2       44.8                     12.0            49.0          181.0     C  
3       41.4                     15.2            53.0          219.0     B  
4       43.5                     27.1            45.0          217.0     B  
5       23.8                     21.0            27.0          153.0     B  
6       22.7                      0.8            18.0          146.0     D  
7       45.9                     12.3            42.0          234.0     B  
8       40.4                     18.6            34.0          148.0     C  
9       57.9                     12.1            55.0          213.0     B

In [85]:
df.corr(numeric_only=True)

age  height_cm  weight_kg  body fat_%  \
age                      1.000000  -0.293980  -0.099966    0.242302   
height_cm               -0.293980   1.000000   0.734909   -0.515440   
weight_kg               -0.099966   0.734909   1.000000   -0.084065   
body fat_%               0.242302  -0.515440  -0.084065    1.000000   
diastolic                0.158508   0.145933   0.262317    0.048059   
systolic                 0.211167   0.210186   0.338943   -0.030376   
gripForce               -0.179583   0.735024   0.700119   -0.541788   
sit and bend forward_cm -0.070033  -0.221970  -0.296249   -0.071225   
sit-ups counts          -0.544581   0.500424   0.294899   -0.608912   
broad jump_cm           -0.435172   0.674589   0.479564   -0.673273   

                         diastolic  systolic  gripForce  \
age                       0.158508  0.211167  -0.179583   
height_cm                 0.145933  0.210186   0.735024   
weight_kg                 0.262317  0.338943   0.700119   
body fat_%                0.048059 -0.030376  -0.541788   
diastolic                 1.000000  0.676309   0.202062   
systolic                  0.676309  1.000000   0.286012   
gripForce                 0.202062  0.286012   1.000000   
sit and bend forward_cm  -0.072098 -0.082434  -0.112577   
sit-ups counts            0.016547  0.056276   0.576669   
broad jump_cm             0.097243  0.152894   0.746853   

                         sit and bend forward_cm  sit-ups counts  \
age                                    -0.070033       -0.544581   
height_cm                              -0.221970        0.500424   
weight_kg                              -0.296249        0.294899   
body fat_%                             -0.071225       -0.608912   
diastolic                              -0.072098        0.016547   
systolic                               -0.082434        0.056276   
gripForce                              -0.112577        0.576669   
sit and bend forward_cm                 1.000000        0.177153   
sit-ups counts                          0.177153        1.000000   
broad jump_cm                           0.026487        0.748273   

                         broad jump_cm  
age                          -0.435172  
height_cm                     0.674589  
weight_kg                     0.479564  
body fat_%                   -0.673273  
diastolic                     0.097243  
systolic                      0.152894  
gripForce                     0.746853  
sit and bend forward_cm       0.026487  
sit-ups counts                0.748273  
broad jump_cm                 1.000000

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      13393 non-null  float64
 1   gender                   13393 non-null  object 
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13393 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13393 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object 
dtypes: float64(10), object(2)
memory usage: 1.2+ MB


In [87]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()
df['class'] = lbl_encoder.fit_transform(df['class'])

In [88]:
df.corr(numeric_only=True)

age  height_cm  weight_kg  body fat_%  \
age                      1.000000  -0.293980  -0.099966    0.242302   
height_cm               -0.293980   1.000000   0.734909   -0.515440   
weight_kg               -0.099966   0.734909   1.000000   -0.084065   
body fat_%               0.242302  -0.515440  -0.084065    1.000000   
diastolic                0.158508   0.145933   0.262317    0.048059   
systolic                 0.211167   0.210186   0.338943   -0.030376   
gripForce               -0.179583   0.735024   0.700119   -0.541788   
sit and bend forward_cm -0.070033  -0.221970  -0.296249   -0.071225   
sit-ups counts          -0.544581   0.500424   0.294899   -0.608912   
broad jump_cm           -0.435172   0.674589   0.479564   -0.673273   
class                    0.065612   0.037753   0.214129    0.341956   

                         diastolic  systolic  gripForce  \
age                       0.158508  0.211167  -0.179583   
height_cm                 0.145933  0.210186   0.735024   
weight_kg                 0.262317  0.338943   0.700119   
body fat_%                0.048059 -0.030376  -0.541788   
diastolic                 1.000000  0.676309   0.202062   
systolic                  0.676309  1.000000   0.286012   
gripForce                 0.202062  0.286012   1.000000   
sit and bend forward_cm  -0.072098 -0.082434  -0.112577   
sit-ups counts            0.016547  0.056276   0.576669   
broad jump_cm             0.097243  0.152894   0.746853   
class                     0.066761  0.035484  -0.136088   

                         sit and bend forward_cm  sit-ups counts  \
age                                    -0.070033       -0.544581   
height_cm                              -0.221970        0.500424   
weight_kg                              -0.296249        0.294899   
body fat_%                             -0.071225       -0.608912   
diastolic                              -0.072098        0.016547   
systolic                               -0.082434        0.056276   
gripForce                              -0.112577        0.576669   
sit and bend forward_cm                 1.000000        0.177153   
sit-ups counts                          0.177153        1.000000   
broad jump_cm                           0.026487        0.748273   
class                                  -0.588123       -0.452832   

                         broad jump_cm     class  
age                          -0.435172  0.065612  
height_cm                     0.674589  0.037753  
weight_kg                     0.479564  0.214129  
body fat_%                   -0.673273  0.341956  
diastolic                     0.097243  0.066761  
systolic                      0.152894  0.035484  
gripForce                     0.746853 -0.136088  
sit and bend forward_cm       0.026487 -0.588123  
sit-ups counts                0.748273 -0.452832  
broad jump_cm                 1.000000 -0.262154  
class                        -0.262154  1.000000

In [89]:
df.describe()

age     height_cm     weight_kg    body fat_%     diastolic  \
count  13393.000000  13393.000000  13393.000000  13393.000000  13393.000000   
mean      36.775106    168.559807     67.447316     23.240165     78.796842   
std       13.625639      8.426583     11.949666      7.256844     10.742033   
min       21.000000    125.000000     26.300000      3.000000      0.000000   
25%       25.000000    162.400000     58.200000     18.000000     71.000000   
50%       32.000000    169.200000     67.400000     22.800000     79.000000   
75%       48.000000    174.800000     75.300000     28.000000     86.000000   
max       64.000000    193.800000    138.100000     78.400000    156.200000   

           systolic     gripForce  sit and bend forward_cm  sit-ups counts  \
count  13393.000000  13393.000000             13393.000000    13393.000000   
mean     130.234817     36.963877                15.209268       39.771224   
std       14.713954     10.624864                 8.456677       14.276698   
min        0.000000      0.000000               -25.000000        0.000000   
25%      120.000000     27.500000                10.900000       30.000000   
50%      130.000000     37.900000                16.200000       41.000000   
75%      141.000000     45.200000                20.700000       50.000000   
max      201.000000     70.500000               213.000000       80.000000   

       broad jump_cm         class  
count   13393.000000  13393.000000  
mean      190.129627      1.500187  
std        39.868000      1.118109  
min         0.000000      0.000000  
25%       162.000000      1.000000  
50%       193.000000      2.000000  
75%       221.000000      3.000000  
max       303.000000      3.000000

In [90]:
X = df.drop(['class'],axis=1)
Y = df['class']

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size = 0.8)

In [92]:
from sklearn.preprocessing import OneHotEncoder
one_hot = OneHotEncoder(sparse_output=False)
one_hot_values = one_hot.fit_transform(X_train[['gender']])
one_hot_df = pd.DataFrame(one_hot_values, columns=one_hot.get_feature_names_out(['gender']))
X_train = pd.concat([X_train.reset_index(drop=True), one_hot_df.reset_index(drop=True)],axis=1)
X_train.drop(columns=['gender'],inplace=True)
one_hot_values = one_hot.transform(X_test[['gender']])
one_hot_df = pd.DataFrame(one_hot_values, columns=one_hot.get_feature_names_out(['gender']))
X_test = pd.concat([X_test.reset_index(drop=True), one_hot_df.reset_index(drop=True)],axis=1)
X_test.drop(columns=['gender'],inplace=True)

In [93]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [94]:
from sklearn.svm import SVC
model = SVC(kernel='poly', degree=6)
model.fit(X_train,Y_train)

SVC(degree=6, kernel='poly')

In [95]:
predict = model.predict(X_test)

In [96]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(Y_test, predict)
print(f'Confusion Matrix: \n{cm} \n {classification_report(Y_test, predict)}')

Confusion Matrix: 
[[556 135  10   1]
 [142 374 123  22]
 [ 48 135 434  39]
 [  7  32 113 508]] 
               precision    recall  f1-score   support

           0       0.74      0.79      0.76       702
           1       0.55      0.57      0.56       661
           2       0.64      0.66      0.65       656
           3       0.89      0.77      0.83       660

    accuracy                           0.70      2679
   macro avg       0.71      0.70      0.70      2679
weighted avg       0.71      0.70      0.70      2679



In [97]:
import pickle
with open('model.pkl','wb') as f:
    pickle.dump((model,Scaler,one_hot,lbl_encoder),f)